### ISSUE TITLE
Mouse over the widgets keeps flashing on macOS when using hover gesture

### ISSUE THREAD

**Issue by Eriice** [MickeyHub/VideoPlayerContainer#3]
[Original]
由于手势检测的视图层级位于 ZStack 的底部，鼠标进入其他控件元素也会被视为离开了手势检测的 Color.clear.contentShape(Rectangle())。

所以当鼠标浮动在控件上方时，会出现控件闪动问题。

可参考 [Reliable mouseEnter/Exit for SwiftUI](https://gist.github.com/importRyan/c668904b0c5442b80b6f38a980595031) 解决

[Translation]
Since the gesture recognization work is placed at the far bottom layer. mouse moving to the other widgets is also taken as leaving the detection area which will trigger the onHover as well.

Therefore, when the mouse stays over other widgets, those widgets will keep flashing.

You can fix this problem with reference to [Reliable mouseEnter/Exit for SwiftUI](https://gist.github.com/importRyan/c668904b0c5442b80b6f38a980595031)

**Comment by shayanbo** [comment]
Thanks for your issue. since I wrote a QuickTime-Example. it's easy for me to reproduce the bug. I've fixed it using a simpler way than your PR - moving `onHover` modifier to the outermost View. You can update the code from the remote repository and try the QuickTime-Example sample project to check if it resolves your confusion as well.
